services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: image_search
    networks:
      - mysql-phpmyadmin
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin

  image-caption-generator:
    image: codait/max-image-caption-generator
    ports:
      - "8081:5000"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmqadmin
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "8082:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
  rabbitmq_data: